"""Create User and Recipe tables

Revision ID: 04151653bcbc
Revises: e3550bad71cf
Create Date: 2025-09-20 23:42:49.426922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04151653bcbc'
down_revision = 'e3550bad71cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipes')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('_password_hash', sa.VARCHAR(length=128), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=250), nullable=True),
    sa.Column('bio', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('instructions', sa.TEXT(), nullable=False),
    sa.Column('minutes_to_complete', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_recipes_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
